package io.github.vvb2060.ims.ui.theme

import androidx.compose.ui.graphics.Color

// Signal Blue light scheme
val primaryLight = Color(0xFF0B5FFF)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDE8FF)
val onPrimaryContainerLight = Color(0xFF00318A)
val secondaryLight = Color(0xFF0078C2)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0EEFF)
val onSecondaryContainerLight = Color(0xFF00344F)
val tertiaryLight = Color(0xFF00A3FF)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9F2FF)
val onTertiaryContainerLight = Color(0xFF003A5A)
val errorLight = Color(0xFFDC2626)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFE2E2)
val onErrorContainerLight = Color(0xFF7F1D1D)
val backgroundLight = Color(0xFFF4F7FC)
val onBackgroundLight = Color(0xFF111827)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF111827)
val surfaceVariantLight = Color(0xFFE3EAF6)
val onSurfaceVariantLight = Color(0xFF475569)
val outlineLight = Color(0xFF6B7A90)
val outlineVariantLight = Color(0xFFC7D3E6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1E293B)
val inverseOnSurfaceLight = Color(0xFFF8FAFC)
val inversePrimaryLight = Color(0xFF9AB8FF)
val surfaceDimLight = Color(0xFFE8EEF8)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8FBFF)
val surfaceContainerLight = Color(0xFFF1F6FF)
val surfaceContainerHighLight = Color(0xFFEAF1FB)
val surfaceContainerHighestLight = Color(0xFFE4ECF8)

// Signal Blue dark scheme
val primaryDark = Color(0xFF9AB8FF)
val onPrimaryDark = Color(0xFF002D7A)
val primaryContainerDark = Color(0xFF0043B5)
val onPrimaryContainerDark = Color(0xFFDCE7FF)
val secondaryDark = Color(0xFF7EC7FF)
val onSecondaryDark = Color(0xFF00344F)
val secondaryContainerDark = Color(0xFF004C73)
val onSecondaryContainerDark = Color(0xFFD0EEFF)
val tertiaryDark = Color(0xFF71D6FF)
val onTertiaryDark = Color(0xFF003548)
val tertiaryContainerDark = Color(0xFF004D67)
val onTertiaryContainerDark = Color(0xFFC8F0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0B1220)
val onBackgroundDark = Color(0xFFE7ECF5)
val surfaceDark = Color(0xFF111827)
val onSurfaceDark = Color(0xFFE7ECF5)
val surfaceVariantDark = Color(0xFF2A3444)
val onSurfaceVariantDark = Color(0xFFBDC9DB)
val outlineDark = Color(0xFF8D9AAF)
val outlineVariantDark = Color(0xFF3B475D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7ECF5)
val inverseOnSurfaceDark = Color(0xFF1A2433)
val inversePrimaryDark = Color(0xFF0B5FFF)
val surfaceDimDark = Color(0xFF0B1220)
val surfaceBrightDark = Color(0xFF2A3444)
val surfaceContainerLowestDark = Color(0xFF070C16)
val surfaceContainerLowDark = Color(0xFF111827)
val surfaceContainerDark = Color(0xFF172132)
val surfaceContainerHighDark = Color(0xFF202C40)
val surfaceContainerHighestDark = Color(0xFF2B3850)
